name 'workspace'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures workspace'
long_description 'Installs/Configures workspace'
version '0.1.0'

depends 'apt'
depends 'timezone-ii'
